using System.Reflection;
using System.Text;

// Emits the D3D11/DXGI enums TiXL uses, with SharpDX's exact member names and values.
string[] d3d11 = ["BindFlags","BlendOperation","BlendOption","ColorWriteMaskFlags","Comparison","CpuAccessFlags",
                  "CullMode","DepthStencilClearFlags","DepthStencilViewDimension","DepthStencilViewFlags",
                  "DepthWriteMask","DeviceCreationFlags","FillMode","Filter","InputClassification","MapFlags","MapMode",
                  "QueryType","RenderTargetViewDimension","ResourceOptionFlags","ResourceUsage",
                  "StencilOperation","TextureAddressMode",
                  "UnorderedAccessViewBufferFlags","UnorderedAccessViewDimension","ShaderResourceViewExtendedBufferFlags"];
string[] direct3D = ["PrimitiveTopology","FeatureLevel","DriverType","ShaderResourceViewDimension"];
string[] dxgi = ["Format","SwapEffect","SwapChainFlags","Usage","WindowAssociationFlags"];

// Format is a shared value type: a backend API needs formats too, and projects store these names, so they
// cannot change anyway. Everything else is D3D11-shaped and belongs to the compatibility layer.
string[] shared = ["Format"];

var compatBuilder = new StringBuilder();
var sharedBuilder = new StringBuilder(); // T3.Graphics

void Header(StringBuilder target, string namespaceName)
{
    target.AppendLine("// <auto-generated>");
    target.AppendLine("// Generated from SharpDX 4.2.0 (MIT licensed) by Spikes/GraphicsEnumGen; see Plan_GraphicsFacade.md.");
    target.AppendLine("// Member names and values are identical to SharpDX on purpose: projects store these by name,");
    target.AppendLine("// shaders and C# structs assume the values, and the D3D11 backend casts between them.");
    target.AppendLine("// </auto-generated>");
    target.AppendLine();
    target.AppendLine($"namespace {namespaceName};");
}

Header(compatBuilder, "T3.Graphics.Compat");
Header(sharedBuilder, "T3.Graphics");

void Emit(Type type)
{
    var builder = shared.Contains(type.Name) ? sharedBuilder : compatBuilder;
    var underlying = Enum.GetUnderlyingType(type);
    var isFlags = type.GetCustomAttribute<FlagsAttribute>() != null;
    builder.AppendLine();
    if (isFlags)
        builder.AppendLine("[Flags]");
    builder.AppendLine($"public enum {type.Name}{(underlying == typeof(int) ? "" : " : " + Alias(underlying))}");
    builder.AppendLine("{");
    foreach (var name in Enum.GetNames(type))
    {
        var value = Convert.ToInt64(Enum.Parse(type, name));
        builder.AppendLine($"    {name} = {(isFlags && value > 9 ? "0x" + value.ToString("X") : value.ToString())},");
    }
    builder.AppendLine("}");
}

static string Alias(Type t) => t == typeof(uint) ? "uint" : t == typeof(long) ? "long" : t == typeof(byte) ? "byte" : t.Name;

foreach (var (assembly, names) in new (Assembly, string[])[]
         {
             (typeof(SharpDX.Direct3D11.Device).Assembly, d3d11),
             (typeof(SharpDX.Direct3D.PrimitiveTopology).Assembly, direct3D),
             (typeof(SharpDX.DXGI.Format).Assembly, dxgi),
         })
{
    foreach (var name in names)
    {
        var type = assembly.GetTypes().FirstOrDefault(t => t.IsEnum && t.Name == name && t.IsPublic);
        if (type == null) { Console.Error.WriteLine($"missing enum {name} in {assembly.GetName().Name}"); continue; }
        Emit(type);
    }
}

File.WriteAllText(args[0], compatBuilder.ToString());
File.WriteAllText(args[1], sharedBuilder.ToString());
Console.WriteLine($"{args[0]}: {compatBuilder.ToString().Split('\n').Length} lines (compat)");
Console.WriteLine($"{args[1]}: {sharedBuilder.ToString().Split('\n').Length} lines (shared)");
