<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)/Tixl.props" />
    <PropertyGroup>
        <TargetFramework>$(TixlNetFrameworkVersion)</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
        <RootNamespace>T3.Core</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <VersionPrefix>$(TixlVersion)</VersionPrefix>
        <VersionSuffix>$(TixlVersionSuffix)</VersionSuffix>
        <InformationalVersion>$(Version)</InformationalVersion>
        <Nullable>disable</Nullable>
        <NoWarn>NU1900;NU1603</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Core.Tests" />
        <InternalsVisibleTo Include="IoServices" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Delaunator" Version="1.0.11" />
        <PackageReference Include="JeremyAnsel.Media.Dds" Version="2.0.7" />
        <PackageReference Include="ManagedBass" Version="4.0.2" />
        <PackageReference Include="ManagedBass.Flac" Version="4.0.2" />
        <PackageReference Include="ManagedBass.Mix" Version="4.0.2" />
        <PackageReference Include="ManagedBass.Wasapi" Version="4.0.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.6.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.10" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="NuGet.Configuration" Version="7.6.0" />
        <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
        <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
        <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
        <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
        <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
        <PackageReference Include="SharpGLTF.Core" Version="1.0.6" />
        <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
    </ItemGroup>

    <ItemGroup>
        <Using Alias="Vector2" Include="System.Numerics.Vector2" />
        <Using Alias="Vector3" Include="System.Numerics.Vector3" />
        <Using Alias="Vector4" Include="System.Numerics.Vector4" />
        <Using Alias="Matrix4x4" Include="System.Numerics.Matrix4x4" />
        <Using Alias="Quaternion" Include="System.Numerics.Quaternion" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Logging\Logging.csproj" />
        <ProjectReference Include="..\Serialization\Serialization.csproj" />
        <ProjectReference Include="..\SystemUi\SystemUi.csproj" />
    </ItemGroup>

</Project>