<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)/Tixl.props" />
    <PropertyGroup>
        <TargetFramework>$(TixlNetCoreFrameworkVersion)</TargetFramework>
        <RootNamespace>T3.Graphics.Vulkan</RootNamespace>
        <AssemblyName>Graphics.Vulkan</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <Deterministic>true</Deterministic>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Vortice.Vulkan" Version="3.2.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Graphics\Graphics.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Core.Tests" />
    </ItemGroup>
</Project>
