using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using ImGuiNET;
using T3.Graphics.Compat;
using T3.Graphics;
using System.Numerics;
using T3.Editor.Gui.Windows.OutputSetup;
using T3.Core.Operator.Slots;
using T3.Core.Rendering;
using T3.Core.Resource;
using T3.Core.SystemUi;
using T3.Editor.App;
using T3.Editor.Gui;
using T3.Editor.Gui.UiHelpers;
using T3.Editor.Gui.Windows;
using T3.Editor.Gui.Windows.Analyze;
using T3.Editor.Gui.Windows.Output;
using T3.Editor.SystemUi;
using T3.Editor.UiModel.ProjectHandling;
using T3.SystemUi;
using Buffer = T3.Graphics.Compat.Buffer;
using Device = T3.Graphics.Compat.Device;
using Vector2 = System.Numerics.Vector2;
using ShaderCompiler = T3.Core.Resource.ShaderCompiling.ShaderCompiler;

namespace T3.Editor.UiContentDrawing;

/// <summary>
/// Renders draw data generated by ImGui with SharpDX render form
/// </summary>
internal sealed class WindowsUiContentDrawer : IUiContentDrawer<Device>
{
    private IntPtr _imguiContext;
    private object _contextLock;
    private ShaderResourceView? _customImageView;

    #region Init
    public void Initialize(Device device, int width, int height, object contextLock, out IntPtr imguiContext)
    {
        if (device == null)
        {
            Log.Error("Can't initialize window without device.");
            BlockingWindow.Instance.ShowMessageBox("Can't initialize rendering device.", "Graphics error");
            EditorUi.Instance.ExitApplication();
            imguiContext = IntPtr.Zero;
            return;
        }

        _device = device;
        _deviceContext = device.ImmediateContext;
        _windowWidth = width;
        _windowHeight = height;
        _contextLock = contextLock;

        lock (_contextLock)
        {
            IntPtr previousContext;

            try
            {
                previousContext = ImGui.GetCurrentContext();
            }
            catch
            {
                // ignored
                previousContext = IntPtr.Zero;
            }

            _imguiContext = ImGui.CreateContext();
            ImGui.SetCurrentContext(_imguiContext);

            SetPerFrameImGuiData(1f / 60f);

            var io = ImGui.GetIO();
            io.BackendFlags |= ImGuiBackendFlags.HasMouseCursors
                             | ImGuiBackendFlags.RendererHasVtxOffset;
            io.ConfigFlags |= ImGuiConfigFlags.DockingEnable;
            SdlImGuiInput.InstallClipboard();

            // ImGui 1.91 error-recovery: stack imbalances (Push/Pop, Begin/End, etc.)
            // are auto-fixed and logged. Recoverable errors appear as:
            //   - Red warning bar in the editor (ConfigErrorRecoveryEnableTooltip)
            //   - [imgui-error] lines in Rider's terminal/stderr (ConfigErrorRecoveryEnableDebugLog)
            // Hard asserts (zero-size buttons, invalid flags) are caught by our
            // try/catch(SEHException) around the render loop.
            //
            // TODO: To get recoverable errors into the managed Log.Warning, build a tiny
            // native shim that hooks ImGuiContext.ErrorCallback and forwards messages to
            // a managed delegate via P/Invoke. See imgui.cpp:10611.
            io.ConfigErrorRecovery = true;
            io.ConfigErrorRecoveryEnableDebugLog = true;
            io.ConfigErrorRecoveryEnableTooltip = true;
            io.ConfigErrorRecoveryEnableAssert = false;   // default is true; suppress native dialog
            // io.ConfigDebugHighlightIdConflicts = false; // enable this to suppress ID conflict overlay
            
            // restore previous context
            if (previousContext != IntPtr.Zero)
            {
                ImGui.SetCurrentContext(previousContext);
            }
        }

        imguiContext = _imguiContext;
    }

    #endregion

    #region Rendering
    public void RenderCallback()
    {
        // An attempt to prevent System.ObjectDisposedException
        if (Program.IsShuttingDown)
            return;

        // Frame-pacing wait via DXGI's FrameLatencyWaitableObject. Must run *before* any other
        // per-frame work so the loop is locked to the swap chain's signalled cadence rather than
        // queueing up speculatively. No-op if the waitable wasn't enabled at swap-chain creation.
        ProgramWindows.Main.WaitForFrameLatency();
        StallWatchdog.NotifyFrameStarted();

        // Vulkan records a frame into one command buffer and submits it after the swap chains are presented;
        // under D3D11 the bracket costs nothing.
        var device = Program.Device!;
        device.BeginFrame();
        try
        {
            RenderFrame();
        }
        finally
        {
            device.EndFrame();
        }
    }

    private void RenderFrame()
    {
        lock (_contextLock)
        {
            ImGui.SetCurrentContext(_imguiContext);
            UiContentUpdate.SetupResourcesAndFontsWithScaling();

            if (ProgramWindows.Main.IsMinimized && UserSettings.Config.SuspendRenderingWhenHidden)
            {
                Thread.Sleep(100);
                return;
            }

            UiContentUpdate.TakeMeasurement();
            ImGui.GetIO().DisplaySize = ProgramWindows.Main.Size;

            ProgramWindows.HandleFullscreenToggle();

            DirtyFlag.IncrementGlobalTicks();
            T3Metrics.UiRenderingStarted();

            if (!string.IsNullOrEmpty(Program.NewImGuiLayoutDefinition))
            {
                ImGui.LoadIniSettingsFromMemory(Program.NewImGuiLayoutDefinition);
                Program.NewImGuiLayoutDefinition = string.Empty;
            }

            // Release any modifier whose key-up we never saw (Alt+Tab between the main and viewer windows is
            // the usual culprit) before it can strand canvas interaction for the whole frame.
            SdlImGuiInput.ReconcileStuckModifiers();

            ImGui.NewFrame();

            // Publish the focused project's setup for operators, then keep the content-source list in
            // step with the live send ops — both independent of which windows are open.
            OutputSetupHandling.UpdateFrame();
            ContentSourceSync.UpdateFrame();

            // Drive projection-mapping outputs: renders each bound output's composite every frame
            // (so its content evaluates even when nothing shows it) and hands it to that output's
            // display window. Must run before any viewer back buffer is bound below.
            OutputPresentation.UpdatePresentation();

            DrawOutputWindows();

            // Render 2nd view
            ProgramWindows.Viewer.SetVisible(T3Ui.ShowSecondaryRenderWindow);

            if (T3Ui.ShowSecondaryRenderWindow)
            {
                var viewer = ProgramWindows.Viewer;
                ProgramWindows.Viewer.PrepareRenderingFrame();

                ProgramWindows.SetVertexShader(SharedResources.FullScreenVertexShaderResource);
                ProgramWindows.SetPixelShader(SharedResources.FullScreenPixelShaderResource);

                if (UserSettings.Config.MirrorUiOnSecondView)
                {
                    if (ProgramWindows.UiCopyTextureSrv != null && !ProgramWindows.UiCopyTextureSrv.IsDisposed)
                    {
                        ProgramWindows.SetRasterizerState(SharedResources.ViewWindowRasterizerState);
                        ProgramWindows.SetPixelShaderSRV(ProgramWindows.UiCopyTextureSrv);
                        ProgramWindows.DrawTextureToSecondaryRenderOutput();
                    }
                }
                else
                {
                    // No texture yet (bound output with nothing composited, or update paused) — the
                    // window just stays cleared this frame. Not an error, so don't log per-frame.
                    if (viewer.Texture is { IsDisposed: false })
                    {
                        if (_viewWindowBackgroundSrv == null ||
                            _viewWindowBackgroundSrv.Resource.NativePointer != viewer.Texture.NativePointer)
                        {
                            _viewWindowBackgroundSrv?.Dispose();
                            _viewWindowBackgroundSrv = new ShaderResourceView(Program.Device, viewer.Texture);
                        }

                        ProgramWindows.SetRasterizerState(SharedResources.ViewWindowRasterizerState);
                        ProgramWindows.SetPixelShaderSRV(_viewWindowBackgroundSrv);
                        ProgramWindows.DrawTextureToSecondaryRenderOutput();
                    }
                }
            }

            ProgramWindows.Main.PrepareRenderingFrame();

            // Clear the main window buffer for next frame
            try
            {
                T3Ui.ProcessFrame();
                ProgramWindows.RefreshViewport();

                ImGui.Render();
                SdlImGuiInput.ApplyRequestedCursor();

                // Presenting the stall overlay discarded the cleared back buffer of this frame.
                if (StallWatchdog.NotifyRenderingBackBuffer())
                    ProgramWindows.Main.PrepareRenderingFrame();

                RenderDrawData(ImGui.GetDrawData());
            }
            catch (SEHException e)
            {
                // A native ImGui assertion fired (e.g. SetCursorPos extent check,
                // invalid BeginChild flags, empty-stack pop). Log the full managed
                // stack trace so the call site is visible in the console/log file
                // alongside the [imgui-error] line that ImGui prints to stderr.
                Log.Error($"ImGui native assertion failed (frame skipped):\n{e}");

                // Try to end the frame so the next NewFrame doesn't assert on
                // "NewFrame called without Render".
                try { ImGui.EndFrame(); } catch { /* best-effort cleanup */ }
            }

            // The UI is in the back buffer now and not yet presented — the one moment a whole-window capture is exact.
            ProgramWindows.ServePendingUiCapture();
        }

        T3Metrics.UiRenderingCompleted();

        ProgramWindows.Present(T3Ui.UseVSync);
    }

    /// <summary>Blits each display-bound output's composite into that display's own window.</summary>
    private static void DrawOutputWindows()
    {
        var outputWindows = OutputWindowHandling.Presenting;
        if (outputWindows.Count == 0)
            return;

        ProgramWindows.SetVertexShader(SharedResources.FullScreenVertexShaderResource);
        ProgramWindows.SetPixelShader(SharedResources.FullScreenPixelShaderResource);
        ProgramWindows.SetRasterizerState(SharedResources.ViewWindowRasterizerState);

        for (var i = 0; i < outputWindows.Count; i++)
        {
            var displayWindow = outputWindows[i];
            var textureView = displayWindow.EnsureTextureView();
            if (textureView == null)
                continue;

            displayWindow.Window.PrepareRenderingFrame();
            ProgramWindows.SetPixelShaderSRV(textureView);
            ProgramWindows.DrawTextureToSecondaryRenderOutput();
        }
    }

    public void InitializeScaling()
    {
        ImGui.GetIO().ConfigFlags |= ImGuiConfigFlags.DpiEnableScaleFonts;
        ImGui.GetIO().ConfigFlags |= ImGuiConfigFlags.DpiEnableScaleViewports;

        unsafe
        {
            // Disable ImGui ini file settings
            ImGui.GetIO().NativePtr->IniFilename = null;
        }
    }

    public void RenderDrawData(ImDrawDataPtr drawData)
    {
        lock (_contextLock)
        {
            PrepareData(drawData);
            DrawData(drawData);
        }
    }

    private void PrepareData(ImDrawDataPtr drawData)
    {
        if (_vb == null || _vertexBufferSize < drawData.TotalVtxCount)
        {
            DisposeObj(ref _vb);
            _vertexBufferSize = drawData.TotalVtxCount + 5000;
            _vb = new Buffer(_device,
                             new BufferDescription()
                                 {
                                     SizeInBytes = _vertexBufferSize * Unsafe.SizeOf<ImDrawVert>(),
                                     Usage = ResourceUsage.Dynamic,
                                     BindFlags = BindFlags.VertexBuffer,
                                     CpuAccessFlags = CpuAccessFlags.Write
                                 });
        }

        if (_ib == null || _indexBufferSize < drawData.TotalIdxCount)
        {
            DisposeObj(ref _ib);
            _indexBufferSize = drawData.TotalIdxCount + 10000;
            _ib = new Buffer(_device,
                             new BufferDescription()
                                 {
                                     SizeInBytes = _indexBufferSize * Unsafe.SizeOf<ushort>(),
                                     Usage = ResourceUsage.Dynamic,
                                     BindFlags = BindFlags.IndexBuffer,
                                     CpuAccessFlags = CpuAccessFlags.Write
                                 });
        }

        // Copy and convert all vertices into a single contiguous buffer
        _deviceContext.MapSubresource(_vb, MapMode.WriteDiscard, T3.Graphics.Compat.MapFlags.None, out var vbStream);
        _deviceContext.MapSubresource(_ib, MapMode.WriteDiscard, T3.Graphics.Compat.MapFlags.None, out var ibStream);
        for (int n = 0; n < drawData.CmdListsCount; n++)
        {
            ImDrawListPtr cmdList = drawData.CmdLists[n];
            vbStream.WriteRange(cmdList.VtxBuffer.Data, (uint)(cmdList.VtxBuffer.Size * Unsafe.SizeOf<ImDrawVert>()));
            ibStream.WriteRange(cmdList.IdxBuffer.Data, (uint)(cmdList.IdxBuffer.Size * Unsafe.SizeOf<ushort>()));
        }

        vbStream.Dispose();
        ibStream.Dispose();
        _deviceContext.UnmapSubresource(_vb, 0);
        _deviceContext.UnmapSubresource(_ib, 0);
    }

    private readonly T3.Graphics.ScissorRect[] _prevScissorRects = new T3.Graphics.ScissorRect[16];

    //Note : mrvux : unless you use multi viewport, you can set to 1, I leave 16 for safety here since it's only called once per frame, better than accumulating GC
    private readonly T3.Graphics.Viewport[] _prevViewports = new T3.Graphics.Viewport[16];

    private void DrawData(ImDrawDataPtr drawData)
    {
        // Setup orthographic projection matrix into our constant buffer
        // Our visible imgui space lies from draw_data->DisplayPos (top left) to draw_data->DisplayPos+data_data->DisplaySize (bottom right). 
        var imGuiIO = ImGui.GetIO();
        var projectionMatrix = Matrix4x4.CreateOrthographicOffCenter(0.0f, imGuiIO.DisplaySize.X, imGuiIO.DisplaySize.Y, 0.0f, -1.0f, 1.0f);

        ResourceUtils.WriteDynamicBufferData<Matrix4x4>(_deviceContext, _vertexConstantBuffer, projectionMatrix);

        // Everything ImGui touches is saved here and put back at the end of the method. This replaces two
        // dozen reads from the driver, which is a thing Vulkan cannot do at all.
        _deviceContext.PushState(StateGroups.All);

        // Setup viewport
        _deviceContext.Rasterizer.SetViewport(0, 0, drawData.DisplaySize.X, drawData.DisplaySize.Y);

        // Bind shader and vertex buffers
        int stride = Unsafe.SizeOf<ImDrawVert>();
        int offset = 0;
        _deviceContext.InputAssembler.InputLayout = _inputLayout;
        _deviceContext.InputAssembler.SetVertexBuffers(0, new VertexBufferBinding(_vb, stride, offset));
        _deviceContext.InputAssembler.SetIndexBuffer(_ib, Format.R16_UInt, 0);
        _deviceContext.InputAssembler.PrimitiveTopology = T3.Graphics.Compat.PrimitiveTopology.TriangleList;
        _deviceContext.VertexShader.SetShader(_vertexShader, null, 0);
        _deviceContext.VertexShader.SetConstantBuffer(0, _vertexConstantBuffer);
        _deviceContext.PixelShader.SetShader(_pixelShader, null, 0);
        _deviceContext.PixelShader.SetSampler(0, _imGuiSampler);

        //make sure we have no tessel/gs
        _deviceContext.HullShader.Set(null);
        _deviceContext.DomainShader.Set(null);
        _deviceContext.GeometryShader.Set(null);

        // Setup render state
        // Note : mrvux do not use properties for blend state / blend, since the native functions are packed with the 
        _deviceContext.OutputMerger.SetBlendState(_blendState, new Vector4(0.0f, 0.0f, 0.0f, 0.0f)); //sample mask to -1, no GC     
        _deviceContext.OutputMerger.SetDepthStencilState(_depthStencilState, 0);
        _deviceContext.Rasterizer.State = _rasterizerState;

        // Render command lists
        int vtxOffset = 0;
        int idxOffset = 0;
        Vector2 pos = drawData.DisplayPos;
        for (int n = 0; n < drawData.CmdListsCount; n++)
        {
            var cmdList = drawData.CmdLists[n];
            for (int cmdI = 0; cmdI < cmdList.CmdBuffer.Size; cmdI++)
            {
                var cmd = cmdList.CmdBuffer[cmdI];
                if (cmd.UserCallback != IntPtr.Zero)
                {
                    throw new NotImplementedException();
                }
                else
                {
                    _deviceContext.Rasterizer.SetScissorRectangle((int)(cmd.ClipRect.X - pos.X), (int)(cmd.ClipRect.Y - pos.Y),
                                                                  (int)(cmd.ClipRect.Z - pos.X), (int)(cmd.ClipRect.W - pos.Y));

                    //This set native pointer without using QueryInterface or new, which allows a "GC free" cast

                    // The draw list carries an id, not a pointer: the view it names may already be gone.
                    _customImageView = ShaderResourceView.FromImGuiTextureId((ulong)cmd.TextureId);
                    _deviceContext.PixelShader.SetShaderResource(0, _customImageView);
                    _deviceContext.DrawIndexed((int)cmd.ElemCount,
                                               idxOffset + (int)cmd.IdxOffset,
                                               vtxOffset + (int)cmd.VtxOffset);

                    //Set to IntPtr.Zero since that would create issue when disposing (on application Exit)
                    //Internally it only resets the pointer and deref the device if it was queried (which in this case, did not)
                    _customImageView = null;
                }
            }

            idxOffset += cmdList.IdxBuffer.Size;
            vtxOffset += cmdList.VtxBuffer.Size;
        }

        // Restore modified DX state
        _deviceContext.PopState();
    }

    private void SetPerFrameImGuiData(float deltaSeconds)
    {
        ImGuiIOPtr io = ImGui.GetIO();
        io.DisplaySize = new Vector2(_windowWidth / _scaleFactor.X, _windowHeight / _scaleFactor.Y);
        io.DisplayFramebufferScale = _scaleFactor;
        io.DeltaTime = deltaSeconds; // DeltaTime is in seconds.
    }
    #endregion

    private bool _initialized;

    #region setup
    [SuppressMessage("ReSharper", "RedundantArgumentDefaultValue")]
    public bool CreateDeviceObjectsAndFonts()
    {
        if (_device == null)
            return false;

        if (!_initialized)
        {
            if (!CreateShaders())
                return false;

            _initialized = true;
        }

        lock (_contextLock)
        {
            lock (StallWatchdog.PresentLock)
            {
                FontAtlasGenerator.CreateFontAtlasWithIcons(_device, _imguiContext, out _fontTextureView, out _imGuiSampler);
                StallOverlay.SnapshotFonts();
            }
        }

        return true;
    }

    /// <summary>
    /// Binds the shaders and states used for ImGui draw data, so other code can draw
    /// <see cref="ImDrawVert"/> geometry with its own vertex and constant buffer.
    /// </summary>
    /// <remarks>Callers on other threads must hold <see cref="StallWatchdog.PresentLock"/>.</remarks>
    internal bool TryBindUiPipeline(DeviceContext context, out ShaderResourceView fontAtlasSrv)
    {
        fontAtlasSrv = _fontTextureView;
        if (!_initialized || _fontTextureView == null || _fontTextureView.IsDisposed)
            return false;

        context.InputAssembler.InputLayout = _inputLayout;
        context.VertexShader.SetShader(_vertexShader, null, 0);
        context.PixelShader.SetShader(_pixelShader, null, 0);
        context.PixelShader.SetSampler(0, _imGuiSampler);
        context.OutputMerger.SetBlendState(_blendState, new Vector4(0.0f, 0.0f, 0.0f, 0.0f));
        context.OutputMerger.SetDepthStencilState(_depthStencilState, 0);
        context.Rasterizer.State = _rasterizerState;
        return true;
    }

    private bool CreateShaders()
    {
        if (_imGuiSampler == null)
            DisposeDeviceObjects();

        // Create the vertex shader
        string vertexShader =
            @"cbuffer vertexBuffer : register(b0) 
                {
                float4x4 ProjectionMatrix; 
                };
                // In the order of the input layout and of ImDrawVert. Vulkan binds vertex attributes by position
                // rather than by semantic, so this order has to match; D3D11 matches semantics and does not mind.
                struct VS_INPUT
                {
                float2 pos : POSITION;
                float2 uv  : TEXCOORD0;
                float4 col : COLOR0;
                };
                
                struct PS_INPUT
                {
                float4 pos : SV_POSITION;
                float4 col : COLOR0;
                float2 uv  : TEXCOORD0;
                };
                
                PS_INPUT main(VS_INPUT input)
                {
                PS_INPUT output;
                output.pos = mul( ProjectionMatrix, float4(input.pos.xy, 0.f, 1.f));
                output.col = input.col;
                output.uv  = input.uv;
                return output;
                }";

        if (!TryCompile(vertexShader, "imgui-vs.hlsl", out _vertexShaderResource))
            return false;

        _vertexShader = _vertexShaderResource;

        // The backend matches the layout against the shader's own reflection, so it needs no bytecode here.
        _inputLayout = new InputLayout(_device, [],
                                       new[]
                                           {
                                               new InputElement("POSITION", 0, Format.R32G32_Float, 0, 0),
                                               new InputElement("TEXCOORD", 0, Format.R32G32_Float, 8, 0),
                                               new InputElement("COLOR", 0, Format.R8G8B8A8_UNorm, 16, 0)
                                           });

        // Create the constant buffer
        _vertexConstantBuffer = ResourceUtils.CreateDynamicConstantBuffer(_device, Unsafe.SizeOf<Matrix4x4>());

        // Create the pixel shader
        string pixelShader =
            @"struct PS_INPUT
                {
                float4 pos : SV_POSITION;
                float4 col : COLOR0;
                float2 uv  : TEXCOORD0;
                };
                sampler sampler0 : register(s0);
                Texture2D texture0 : register(t0);
                
                float4 main(PS_INPUT input) : SV_Target
                {
                float4 out_col = input.col * texture0.Sample(sampler0, input.uv); 
                return out_col; 
                }";

        if (!TryCompile(pixelShader, "imgui-ps.hlsl", out _pixelShaderResource))
            return false;

        _pixelShader = _pixelShaderResource;

        // Create the blending setup
        var blendDesc = new BlendStateDescription() { AlphaToCoverageEnable = false, IndependentBlendEnable = false };
        blendDesc.RenderTarget[0].IsBlendEnabled = true;
        blendDesc.RenderTarget[0].SourceBlend = BlendOption.SourceAlpha;
        blendDesc.RenderTarget[0].DestinationBlend = BlendOption.InverseSourceAlpha;
        blendDesc.RenderTarget[0].BlendOperation = BlendOperation.Add;
        blendDesc.RenderTarget[0].SourceAlphaBlend = BlendOption.InverseSourceAlpha;
        blendDesc.RenderTarget[0].DestinationAlphaBlend = BlendOption.Zero;
        blendDesc.RenderTarget[0].AlphaBlendOperation = BlendOperation.Add;
        blendDesc.RenderTarget[0].RenderTargetWriteMask = ColorWriteMaskFlags.All;
        _blendState = new BlendState(_device, blendDesc);

        // Create the rasterizer state
        var rasterizerDesc = new RasterizerStateDescription()
                                 {
                                     FillMode = FillMode.Solid,
                                     CullMode = CullMode.None,
                                     IsScissorEnabled = true,
                                     IsDepthClipEnabled = true
                                 };
        _rasterizerState = new RasterizerState(_device, rasterizerDesc);

        // Create depth-stencil State
        var depthStencilDesc = new DepthStencilStateDescription()
                                   {
                                       IsDepthEnabled = false,
                                       DepthWriteMask = DepthWriteMask.All,
                                       DepthComparison = Comparison.Always,
                                       IsStencilEnabled = false
                                   };
        depthStencilDesc.FrontFace.FailOperation =
            depthStencilDesc.FrontFace.DepthFailOperation = depthStencilDesc.FrontFace.PassOperation = StencilOperation.Keep;

        depthStencilDesc.BackFace = depthStencilDesc.FrontFace;
        _depthStencilState = new DepthStencilState(_device, depthStencilDesc);
        return true;
    }



    public void Dispose()
    {
        DisposeDeviceObjects();
    }

    /// <summary>
    /// Compiles through the platform's shader compiler rather than FXC directly, which does not exist outside
    /// Windows. These shaders have no includes and no operator behind them, so they are compiled without an owner.
    /// </summary>
    private static bool TryCompile<TShader>(string source, string name, [NotNullWhen(true)] out TShader shader)
        where TShader : T3.Core.DataTypes.AbstractShader
    {
        var args = new ShaderCompiler.ShaderCompilationArgs(source, "main", null, name, null);
        if (ShaderCompiler.TryCompileShaderFromSource(args, useCache: true, forceRecompile: false, out shader, out var reason))
            return true;

        Log.Error($"Could not compile the ImGui shader {name}: {reason}");
        return false;
    }

    private void DisposeObj<T>(ref T obj) where T : class, IDisposable
    {
        obj?.Dispose();
        obj = null;
    }

    private void DisposeDeviceObjects()
    {
        if (_device == null)
            return;

        try
        {
            // Sadly a resource leak causes this to trigger memory exceptions.
            // So disabled for now

            DisposeObj(ref _imGuiSampler);
            DisposeObj(ref _fontTextureView);
            DisposeObj(ref _ib);
            DisposeObj(ref _vb);
            DisposeObj(ref _blendState);
            DisposeObj(ref _depthStencilState);
            DisposeObj(ref _rasterizerState);
            DisposeObj(ref _pixelShaderResource);
            _pixelShader = null;
            DisposeObj(ref _vertexConstantBuffer);
            DisposeObj(ref _inputLayout);
            DisposeObj(ref _vertexShaderResource);
            _vertexShader = null;
        }
        catch (Exception e)
        {
            Log.Warning($"Failed to dispose resources :{e.Message}");
        }
    }
    #endregion

    private Device _device;
    private DeviceContext _deviceContext;
    private Buffer _vb;
    private Buffer _ib;
    private T3.Core.DataTypes.VertexShader _vertexShaderResource;
    private VertexShader _vertexShader;
    private InputLayout _inputLayout;
    private Buffer _vertexConstantBuffer;
    private T3.Core.DataTypes.PixelShader _pixelShaderResource;
    private PixelShader _pixelShader;
    private SamplerState _imGuiSampler;
    private ShaderResourceView _fontTextureView;
    private RasterizerState _rasterizerState;
    private BlendState _blendState;
    private DepthStencilState _depthStencilState;
    private int _vertexBufferSize = 5000, _indexBufferSize = 1000;

    private int _windowWidth;
    private int _windowHeight;
    private static ShaderResourceView _viewWindowBackgroundSrv;

    private readonly Vector2 _scaleFactor = Vector2.One;
}