<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)/Tixl.props" />
    <PropertyGroup>
        <TargetFramework>$(TixlNetFrameworkVersion)</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TiXL.DebugClient</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>
</Project>
