// <auto-generated>
// Generated from SharpDX 4.2.0 (MIT licensed) by Spikes/GraphicsEnumGen; see Plan_GraphicsFacade.md.
// Member names and values are identical to SharpDX on purpose: projects store these by name,
// shaders and C# structs assume the values, and the D3D11 backend casts between them.
// </auto-generated>

namespace T3.Graphics.Compat;

[Flags]
public enum BindFlags
{
    None = 0,
    VertexBuffer = 1,
    IndexBuffer = 2,
    ConstantBuffer = 4,
    ShaderResource = 8,
    StreamOutput = 0x10,
    RenderTarget = 0x20,
    DepthStencil = 0x40,
    UnorderedAccess = 0x80,
    Decoder = 0x200,
    VideoEncoder = 0x400,
}

public enum BlendOperation
{
    Add = 1,
    Subtract = 2,
    ReverseSubtract = 3,
    Minimum = 4,
    Maximum = 5,
}

public enum BlendOption
{
    Zero = 1,
    One = 2,
    SourceColor = 3,
    InverseSourceColor = 4,
    SourceAlpha = 5,
    InverseSourceAlpha = 6,
    DestinationAlpha = 7,
    InverseDestinationAlpha = 8,
    DestinationColor = 9,
    InverseDestinationColor = 10,
    SourceAlphaSaturate = 11,
    BlendFactor = 14,
    InverseBlendFactor = 15,
    SecondarySourceColor = 16,
    InverseSecondarySourceColor = 17,
    SecondarySourceAlpha = 18,
    InverseSecondarySourceAlpha = 19,
}

[Flags]
public enum ColorWriteMaskFlags : byte
{
    Red = 1,
    Green = 2,
    Blue = 4,
    Alpha = 8,
    All = 0xF,
}

public enum Comparison
{
    Never = 1,
    Less = 2,
    Equal = 3,
    LessEqual = 4,
    Greater = 5,
    NotEqual = 6,
    GreaterEqual = 7,
    Always = 8,
}

[Flags]
public enum CpuAccessFlags
{
    None = 0,
    Write = 0x10000,
    Read = 0x20000,
}

public enum CullMode
{
    None = 1,
    Front = 2,
    Back = 3,
}

[Flags]
public enum DepthStencilClearFlags
{
    Depth = 1,
    Stencil = 2,
}

public enum DepthStencilViewDimension
{
    Unknown = 0,
    Texture1D = 1,
    Texture1DArray = 2,
    Texture2D = 3,
    Texture2DArray = 4,
    Texture2DMultisampled = 5,
    Texture2DMultisampledArray = 6,
}

[Flags]
public enum DepthStencilViewFlags
{
    None = 0,
    ReadOnlyDepth = 1,
    ReadOnlyStencil = 2,
}

public enum DepthWriteMask
{
    Zero = 0,
    All = 1,
}

[Flags]
public enum DeviceCreationFlags
{
    None = 0,
    SingleThreaded = 1,
    Debug = 2,
    SwitchToRef = 4,
    PreventThreadingOptimizations = 8,
    BgraSupport = 0x20,
    Debuggable = 0x40,
    PreventAlteringLayerSettingsFromRegistry = 0x80,
    DisableGpuTimeout = 0x100,
    VideoSupport = 0x800,
}

public enum FillMode
{
    Wireframe = 2,
    Solid = 3,
}

public enum Filter
{
    MinMagMipPoint = 0,
    MinMagPointMipLinear = 1,
    MinPointMagLinearMipPoint = 4,
    MinPointMagMipLinear = 5,
    MinLinearMagMipPoint = 16,
    MinLinearMagPointMipLinear = 17,
    MinMagLinearMipPoint = 20,
    MinMagMipLinear = 21,
    Anisotropic = 85,
    ComparisonMinMagMipPoint = 128,
    ComparisonMinMagPointMipLinear = 129,
    ComparisonMinPointMagLinearMipPoint = 132,
    ComparisonMinPointMagMipLinear = 133,
    ComparisonMinLinearMagMipPoint = 144,
    ComparisonMinLinearMagPointMipLinear = 145,
    ComparisonMinMagLinearMipPoint = 148,
    ComparisonMinMagMipLinear = 149,
    ComparisonAnisotropic = 213,
    MinimumMinMagMipPoint = 256,
    MinimumMinMagPointMipLinear = 257,
    MinimumMinPointMagLinearMipPoint = 260,
    MinimumMinPointMagMipLinear = 261,
    MinimumMinLinearMagMipPoint = 272,
    MinimumMinLinearMagPointMipLinear = 273,
    MinimumMinMagLinearMipPoint = 276,
    MinimumMinMagMipLinear = 277,
    MinimumAnisotropic = 341,
    MaximumMinMagMipPoint = 384,
    MaximumMinMagPointMipLinear = 385,
    MaximumMinPointMagLinearMipPoint = 388,
    MaximumMinPointMagMipLinear = 389,
    MaximumMinLinearMagMipPoint = 400,
    MaximumMinLinearMagPointMipLinear = 401,
    MaximumMinMagLinearMipPoint = 404,
    MaximumMinMagMipLinear = 405,
    MaximumAnisotropic = 469,
}

public enum InputClassification
{
    PerVertexData = 0,
    PerInstanceData = 1,
}

[Flags]
public enum MapFlags
{
    None = 0,
    DoNotWait = 0x100000,
}

public enum MapMode
{
    Read = 1,
    Write = 2,
    ReadWrite = 3,
    WriteDiscard = 4,
    WriteNoOverwrite = 5,
}

public enum QueryType
{
    Event = 0,
    Occlusion = 1,
    Timestamp = 2,
    TimestampDisjoint = 3,
    PipelineStatistics = 4,
    OcclusionPredicate = 5,
    StreamOutputStatistics = 6,
    StreamOutputOverflowPredicate = 7,
    StreamOutputStatisticsStream0 = 8,
    StreamOutputOverflowPredicateStream0 = 9,
    StreamOutputStatisticsStream1 = 10,
    StreamOutputOverflowPredicateStream1 = 11,
    StreamOutputStatisticsStream2 = 12,
    StreamOutputOverflowPredicateStream2 = 13,
    StreamOutputStatisticsStream3 = 14,
    StreamOutputOverflowPredicateStream3 = 15,
}

public enum RenderTargetViewDimension
{
    Unknown = 0,
    Buffer = 1,
    Texture1D = 2,
    Texture1DArray = 3,
    Texture2D = 4,
    Texture2DArray = 5,
    Texture2DMultisampled = 6,
    Texture2DMultisampledArray = 7,
    Texture3D = 8,
}

[Flags]
public enum ResourceOptionFlags
{
    None = 0,
    GenerateMipMaps = 1,
    Shared = 2,
    TextureCube = 4,
    DrawIndirectArguments = 0x10,
    BufferAllowRawViews = 0x20,
    BufferStructured = 0x40,
    ResourceClamp = 0x80,
    SharedKeyedmutex = 0x100,
    GdiCompatible = 0x200,
    SharedNthandle = 0x800,
    RestrictedContent = 0x1000,
    RestrictSharedResource = 0x2000,
    RestrictSharedResourceDriver = 0x4000,
    Guarded = 0x8000,
    TilePool = 0x20000,
    Tiled = 0x40000,
    HwProtected = 0x80000,
}

public enum ResourceUsage
{
    Default = 0,
    Immutable = 1,
    Dynamic = 2,
    Staging = 3,
}

public enum StencilOperation
{
    Keep = 1,
    Zero = 2,
    Replace = 3,
    IncrementAndClamp = 4,
    DecrementAndClamp = 5,
    Invert = 6,
    Increment = 7,
    Decrement = 8,
}

public enum TextureAddressMode
{
    Wrap = 1,
    Mirror = 2,
    Clamp = 3,
    Border = 4,
    MirrorOnce = 5,
}

[Flags]
public enum UnorderedAccessViewBufferFlags
{
    None = 0,
    Raw = 1,
    Append = 2,
    Counter = 4,
}

public enum UnorderedAccessViewDimension
{
    Unknown = 0,
    Buffer = 1,
    Texture1D = 2,
    Texture1DArray = 3,
    Texture2D = 4,
    Texture2DArray = 5,
    Texture3D = 8,
}

[Flags]
public enum ShaderResourceViewExtendedBufferFlags
{
    None = 0,
    Raw = 1,
}

public enum ResourceDimension
{
    Unknown = 0,
    Buffer = 1,
    Texture1D = 2,
    Texture2D = 3,
    Texture3D = 4,
}

[Flags]
public enum FormatSupport
{
    None = 0,
    Buffer = 1,
    InputAssemblyVertexBuffer = 2,
    InputAssemblyIndexBuffer = 4,
    StreamOutputBuffer = 8,
    Texture1D = 0x10,
    Texture2D = 0x20,
    Texture3D = 0x40,
    TextureCube = 0x80,
    ShaderLoad = 0x100,
    ShaderSample = 0x200,
    ShaderSampleComparison = 0x400,
    ShaderSampleMonoText = 0x800,
    Mip = 0x1000,
    MipAutogen = 0x2000,
    RenderTarget = 0x4000,
    Blendable = 0x8000,
    DepthStencil = 0x10000,
    CpuLockable = 0x20000,
    MultisampleResolve = 0x40000,
    Display = 0x80000,
    CastWithinBitLayout = 0x100000,
    MultisampleRenderTarget = 0x200000,
    MultisampleLoad = 0x400000,
    ShaderGather = 0x800000,
    BackBufferCast = 0x1000000,
    TypedUnorderedAccessView = 0x2000000,
    ShaderGatherComparison = 0x4000000,
    DecoderOutput = 0x8000000,
    VideoProcessorOutput = 0x10000000,
    VideoProcessorInput = 0x20000000,
    VideoEncoder = 0x40000000,
}

public enum PrimitiveTopology
{
    Undefined = 0,
    PointList = 1,
    LineList = 2,
    LineStrip = 3,
    TriangleList = 4,
    TriangleStrip = 5,
    LineListWithAdjacency = 10,
    LineStripWithAdjacency = 11,
    TriangleListWithAdjacency = 12,
    TriangleStripWithAdjacency = 13,
    PatchListWith1ControlPoints = 33,
    PatchListWith2ControlPoints = 34,
    PatchListWith3ControlPoints = 35,
    PatchListWith4ControlPoints = 36,
    PatchListWith5ControlPoints = 37,
    PatchListWith6ControlPoints = 38,
    PatchListWith7ControlPoints = 39,
    PatchListWith8ControlPoints = 40,
    PatchListWith9ControlPoints = 41,
    PatchListWith10ControlPoints = 42,
    PatchListWith11ControlPoints = 43,
    PatchListWith12ControlPoints = 44,
    PatchListWith13ControlPoints = 45,
    PatchListWith14ControlPoints = 46,
    PatchListWith15ControlPoints = 47,
    PatchListWith16ControlPoints = 48,
    PatchListWith17ControlPoints = 49,
    PatchListWith18ControlPoints = 50,
    PatchListWith19ControlPoints = 51,
    PatchListWith20ControlPoints = 52,
    PatchListWith21ControlPoints = 53,
    PatchListWith22ControlPoints = 54,
    PatchListWith23ControlPoints = 55,
    PatchListWith24ControlPoints = 56,
    PatchListWith25ControlPoints = 57,
    PatchListWith26ControlPoints = 58,
    PatchListWith27ControlPoints = 59,
    PatchListWith28ControlPoints = 60,
    PatchListWith29ControlPoints = 61,
    PatchListWith30ControlPoints = 62,
    PatchListWith31ControlPoints = 63,
    PatchListWith32ControlPoints = 64,
}

public enum FeatureLevel
{
    Level_9_1 = 37120,
    Level_9_2 = 37376,
    Level_9_3 = 37632,
    Level_10_0 = 40960,
    Level_10_1 = 41216,
    Level_11_0 = 45056,
    Level_11_1 = 45312,
    Level_12_0 = 49152,
    Level_12_1 = 49408,
}

public enum DriverType
{
    Unknown = 0,
    Hardware = 1,
    Reference = 2,
    Null = 3,
    Software = 4,
    Warp = 5,
}

public enum ShaderResourceViewDimension
{
    Unknown = 0,
    Buffer = 1,
    Texture1D = 2,
    Texture1DArray = 3,
    Texture2D = 4,
    Texture2DArray = 5,
    Texture2DMultisampled = 6,
    Texture2DMultisampledArray = 7,
    Texture3D = 8,
    TextureCube = 9,
    TextureCubeArray = 10,
    ExtendedBuffer = 11,
}

public enum SwapEffect
{
    Discard = 0,
    Sequential = 1,
    FlipSequential = 3,
    FlipDiscard = 4,
}

[Flags]
public enum SwapChainFlags
{
    None = 0,
    Nonprerotated = 1,
    AllowModeSwitch = 2,
    GdiCompatible = 4,
    RestrictedContent = 8,
    RestrictSharedResourceDriver = 0x10,
    DisplayOnly = 0x20,
    FrameLatencyWaitAbleObject = 0x40,
    ForegroundLayer = 0x80,
    FullScreenVideo = 0x100,
    YuvVideo = 0x200,
    HwProtected = 0x400,
    AllowTearing = 0x800,
    RestrictedToAllHolographicDisplayS = 0x1000,
}

[Flags]
public enum Usage
{
    ShaderInput = 0x10,
    RenderTargetOutput = 0x20,
    BackBuffer = 0x40,
    Shared = 0x80,
    ReadOnly = 0x100,
    DiscardOnPresent = 0x200,
    UnorderedAccess = 0x400,
}

[Flags]
public enum WindowAssociationFlags
{
    None = 0,
    IgnoreAll = 1,
    IgnoreAltEnter = 2,
    IgnorePrintScreen = 4,
    Valid = 7,
}
