name: "Publish"
description: "Run common build steps"
runs:
  using: "composite"
  steps:
  - name: Install innosetup
    uses: crazy-max/ghaction-chocolatey@v3
    with:
      args: install innosetup

  - name: Download dotnet-sdk and VC_redist
    shell: pwsh
    run: |
      New-Item -ItemType Directory -Force -Path Installer\dependencies\downloads
      Invoke-WebRequest -Uri "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.102/dotnet-sdk-9.0.102-win-x64.exe" -OutFile "Installer\dependencies\downloads\dotnet-sdk-9.0.102-win-x64.exe"
      Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "Installer\dependencies\downloads\VC_redist.x64.exe"

  - name: Package Application
    shell: pwsh
    run: iscc Installer\installer.iss /DMyAppName=Tooll-v${{ github.event.release.tag_name }} /DMyAppVersion=${{ github.event.release.tag_name }}

 