; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Build complete release before packaging (publish Player + build Editor)
#expr Exec("powershell", "-ExecutionPolicy Bypass -File build-release.ps1", ".", 1, SW_SHOW)

#define MyAppVersion "4.3.0.2"
#define MyAppName "TiXL-v4.3.0.2"
#define MyAppPublisher "TiXL Community"
#define MyAppURL "https://tixl.app//"
#define MyAppExeName "TiXL.exe"
#define DotNetSdkInstaller "dotnet-sdk-10.0.201-win-x64.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=t3.tixl
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\TiXL\TiXL {#MyAppVersion}
UsePreviousAppDir=no 

; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes

; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest

OutputDir=.\Output
OutputBaseFilename=Tixl-v{#MyAppVersion}
SetupIconFile=..\EditorResources\images\t3.ico 
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\Editor\bin\Release\net10.0-windows\*"; DestDir: "{app}"; Excludes: "*.proxy.mov,*.waveform.png,*.waveform.jpg,win-x86,win-arm64,osx*,linux-*,android*,ios,maccatalyst-*,unix"; Flags: ignoreversion recursesubdirs
; Operator thumbnails live next to the source projects in .meta\Thumbnails\ and are not copied
; into the build output by the csproj content rules. Pull them straight from the source tree so
; they ship with the release.
Source: "..\Operators\Lib\.meta\*";      DestDir: "{app}\Operators\Lib\.meta";      Excludes: "*.proxy.mov,*.waveform.png,*.waveform.jpg,win-x86,win-arm64,osx*,linux-*,android*,ios,maccatalyst-*,unix"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\Operators\Examples\.meta\*"; DestDir: "{app}\Operators\Examples\.meta"; Excludes: "*.proxy.mov,*.waveform.png,*.waveform.jpg,win-x86,win-arm64,osx*,linux-*,android*,ios,maccatalyst-*,unix"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "dependencies\downloads\{#DotNetSdkInstaller}"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "dependencies\downloads\VC_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "..\.Defaults\Tests\*"; DestDir: "{userappdata}\TiXL\Tests"; Excludes: "*.proxy.mov,*.waveform.png,*.waveform.jpg,win-x86,win-arm64,osx*,linux-*,android*,ios,maccatalyst-*,unix"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Code]
// Returns the numeric field before the next '.' and removes it from Rest; -1 if not numeric.
function TakeVersionPart(var Rest: string): Integer;
var
  DotPos: Integer;
begin
  DotPos := Pos('.', Rest);
  if DotPos = 0 then
  begin
    Result := StrToIntDef(Rest, -1);
    Rest := '';
  end
  else
  begin
    Result := StrToIntDef(Copy(Rest, 1, DotPos - 1), -1);
    Rest := Copy(Rest, DotPos + 1, Length(Rest));
  end;
end;

// Any release SDK of major 10 at or above the bundled 10.0.201 is enough.
// The SDK installer registers versions as value names in the 32-bit registry view.
function GetDotNetSdkInstalled: Boolean;
var
  Versions: TArrayOfString;
  I, Major, Minor, Patch: Integer;
  Rest: string;
begin
  Result := False;
  if not RegGetValueNames(HKLM32, 'SOFTWARE\dotnet\Setup\InstalledVersions\x64\sdk', Versions) then
    Exit;

  for I := 0 to GetArrayLength(Versions) - 1 do
  begin
    Rest := Versions[I];
    if Pos('-', Rest) > 0 then
      Continue;

    Major := TakeVersionPart(Rest);
    Minor := TakeVersionPart(Rest);
    Patch := TakeVersionPart(Rest);
    if (Major = 10) and ((Minor > 0) or ((Minor = 0) and (Patch >= 201))) then
    begin
      Result := True;
      Exit;
    end;
  end;
end;

function GetvcruntimeVersion: Boolean;
begin
  Result := FileExists('C:\Windows\System32\vcruntime140.dll');
end;

[Run]
Filename: "{tmp}\{#DotNetSdkInstaller}"; StatusMsg: "Install .NET 10 SDK"; Check: not GetDotNetSdkInstalled
Filename: "{tmp}\VC_redist.x64.exe"; StatusMsg: "Install Visual C++ Redistributable"; check: not GetvcruntimeVersion 
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent